package main.Enums;

public enum PropertyNames {

    MEDITERRANEAN_AVENUE,
    BALTIC_AVENUE,
    ORIENTAL_AVENUE,
    VERMONT_AVENUE,
    CONNECTICUT_AVENUE,
    ST_CHARLES_PLACE,
    STATES_AVENUE,
    VIRGINIA_AVENUE,
    ST_JAMES_PLACE,
    TENNESSEE_AVENUE,
    NEW_YORK_AVENUE,
    KENTUCKY_AVENUE,
    INDIANA_AVENUE,
    ILLINOIS_AVENUE,
    ATLANTIC_AVENUE,
    VENTNOR_AVENUE,
    MARVIN_GARDENS,
    PACIFIC_AVENUE,
    NORTH_CAROLINA_AVENUE,
    PENNSYLVANIA_AVENUE,
    PARK_PLACE,
    BOARDWALK,

    ELECTRIC_COMPANY,
    WATER_WORKS,

    READING_RAILROAD,
    PENNSYLVANIA_RAILROAD,
    B_AND_O_RAILROAD,
    SHORT_LINE_RAILROAD;



}
