import java.util.ArrayList;
import java.util.Arrays;

public class InitValues {

    public ArrayList<String> propertyName = new ArrayList<>(Arrays.asList(
            "Mediterranean Avenue",
            "Baltic Avenue",
            "Oriental Avenue",
            "Vermont Avenue",
            "Connecticut Avenue",
            "St. Charles Place",
            "States Avenue",
            "Virginia Avenue",
            "St. James Place",
            "Tennessee Avenue",
            "New York Avenue",
            "Kentucky Avenue",
            "Indiana Avenue",
            "Illinois Avenue",
            "Atlantic Avenue",
            "Ventnor Avenue",
            "Marvin Gardens",
            "Pacific Avenue",
            "North Carolina Avenue",
            "Pennsylvania Avenue",
            "Park Place",
            "Boardwalk",
            "Reading Railroad",
            "Pennsylvania RailRoad",
            "B&O RailRoad",
            "Short Line",
            "Electric Company",
            "Water Works"));

    public ArrayList<Integer> propertyCost = new ArrayList<>(Arrays.asList(
            60,
            60,
            100,
            100,
            120,
            140,
            140,
            160,
            180,
            180,
            200,
            220,
            220,
            240,
            260,
            260,
            280,
            300,
            300,
            320,
            350,
            400,
            200,
            200,
            200,
            200,
            150,
            150));

    public ArrayList<String> propertyColor = new ArrayList<>(Arrays.asList(
            "brown",
            "brown",
            "lightBlue",
            "lightBlue",
            "lightBlue",
            "lightBlue",
            "pink",
            "pink",
            "pink",
            "orange",
            "orange",
            "orange",
            "red",
            "yellow",
            "yellow",
            "yellow",
            "green",
            "green",
            "green",
            "darkBlue",
            "darkBlue",
            "black",
            "black",
            "black",
            "black",
            "white",
            "white"));

    // hotel allowed
    // house allowed
}
